import { combineReducers } from 'redux';
import LibraryReducer from './LibraryReducer';
import SelectionReducer from './SelectionReducer';

export default combineReducers({
    // Whatever key is provided for each reducer will show up on the state object
    // libraries reducer always returns an array; 
    // whenever this reducer runs it will return a list of libraries to the user
    // LibraryReducer assigned to the key libraries in state
    // When console.log(store.getState()) = { libraries: [] }
    libraries: LibraryReducer,
    selectedLibraryId: SelectionReducer // value for selectedLibraryId key will be generated by SelectionReducer
});